"""Static (offline-buffer) diagnostic metrics, stratified by cell.

These metrics describe the *offline dataset* generated by the behaviour
policy — they are computed once before training begins and do not vary
with the trained policy.  A time series isn't the right idiom for
per-run static summaries; a box plot per cell is.

The complementary module ``metrics_curves`` plots the metrics that
*do* evolve during training (the six Δ-divergence variants).
"""

from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

from causal_rl.plotting.style import apply_style

_ID_STATUS_COLORS = {"id": "#4CAF50", "partial_id": "#FF9800", "non_id": "#F44336"}

_PANELS: tuple[tuple[str, str, str], ...] = (
    # (csv_column, title, subtitle)
    (
        "min_propensity",
        "min propensity",
        "lower → coverage broken on at least one (s, a)",
    ),
    (
        "ess_ratio",
        "ESS / N",
        "lower → buffer over-represents some (s, a)",
    ),
    (
        "coverage_ess_histogram",
        "ESS_histogram / N",
        "lower → action support is sparse",
    ),
    (
        "coverage_action_freq_min",
        "min action freq",
        "0 → at least one action never observed",
    ),
    (
        "propensity_calibration_ece",
        "ECE (π_b model)",
        "higher → propensity model misfit",
    ),
    (
        "bound_width_mean",
        "Bareinboim natural-bound width",
        "0.875 = uniform π_b floor (n_actions=8)",
    ),
)


def _safe_float(val: object) -> float:
    if val is None or val == "" or val == "nan":
        return float("nan")
    try:
        return float(val)  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return float("nan")


def _read_last_row(path: Path) -> dict[str, str] | None:
    with path.open("r", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    return rows[-1] if rows else None


def make_static_diagnostics(
    results_dir: Path,
    output_dir: Path,
    env_prefix: str | None = None,
) -> None:
    """One row of six box-plot panels, one box per cell.

    Each box aggregates final-checkpoint values across runs in that cell.
    Panels with all-NaN columns render a "not collected" annotation
    rather than an empty plot.
    """
    apply_style()
    output_dir.mkdir(parents=True, exist_ok=True)
    # per_cell[cell][metric] = list[float] (final-checkpoint value per run)
    per_cell: dict[int, dict[str, list[float]]] = defaultdict(
        lambda: defaultdict(list)
    )
    cell_id_status: dict[int, str] = {}
    for path in results_dir.rglob("eval.csv"):
        last = _read_last_row(path)
        if last is None:
            continue
        if env_prefix is not None and not str(last.get("env_name", "")).startswith(
            env_prefix
        ):
            continue
        try:
            cell = int(last.get("cell", 0))
        except (TypeError, ValueError):
            continue
        cell_id_status.setdefault(cell, str(last.get("id_status", "non_id")))
        for col, _, _ in _PANELS:
            v = _safe_float(last.get(col))
            if np.isfinite(v):
                per_cell[cell][col].append(v)
    if not per_cell:
        print("[static_diagnostics] no eval.csv rows found; skipping.")
        return

    cells = sorted(per_cell.keys())
    fig, axes = plt.subplots(2, 3, figsize=(13.0, 6.0))
    for ax, (col, title, subtitle) in zip(axes.flat, _PANELS, strict=True):
        data: list[list[float]] = []
        labels: list[str] = []
        colors: list[str] = []
        for cell in cells:
            vals = per_cell[cell].get(col, [])
            if vals:
                data.append(vals)
                status = cell_id_status.get(cell, "non_id")
                labels.append(f"C{cell}\n({status})")
                colors.append(_ID_STATUS_COLORS.get(status, "gray"))
        if not data:
            ax.text(
                0.5,
                0.5,
                "not collected",
                transform=ax.transAxes,
                ha="center",
                va="center",
                fontsize=8,
                color="#888888",
                style="italic",
            )
            ax.set_title(title, fontsize=10)
            continue
        try:
            bp = ax.boxplot(
                data,
                tick_labels=labels,
                patch_artist=True,
                medianprops={"color": "black"},
            )
        except TypeError:
            bp = ax.boxplot(
                data,
                labels=labels,
                patch_artist=True,
                medianprops={"color": "black"},
            )
        for patch, color in zip(bp["boxes"], colors, strict=True):
            patch.set_facecolor(color)
            patch.set_alpha(0.6)
        ax.set_title(title, fontsize=10)
        ax.set_xlabel(subtitle, fontsize=7, color="#555555", style="italic")
        ax.tick_params(axis="both", labelsize=8)

    fig.suptitle(
        "Static offline-buffer diagnostics by cell  ·  per-run summaries, not trajectories",
        fontsize=12,
    )
    fig.tight_layout(rect=(0, 0, 1, 0.96))
    pdf = output_dir / "static_diagnostics.pdf"
    png = output_dir / "static_diagnostics.png"
    fig.savefig(pdf, bbox_inches="tight")
    fig.savefig(png, dpi=300, bbox_inches="tight")
    plt.close(fig)
