from __future__ import annotations

# Per-arm bound columns.  Eight arms is hard-coded in the runner's discrete
# action setup (see runner.py:n_actions=8).  Per-arm bounds and counts are
# emitted at every checkpoint so figures like ``bound_width_panel`` can
# scatter individual arms instead of a degenerate per-run mean.
_BOUND_COLUMNS_PER_ARM = (
    [f"bound_lower_a{a}" for a in range(8)]
    + [f"bound_upper_a{a}" for a in range(8)]
    + [f"obs_arm_count_a{a}" for a in range(8)]
)

TRAIN_COLUMNS = [
    "step",
    "episode",
    "wall_time",
    "cell",
    "env_name",
    "env_fidelity",
    "algorithm",
    "behaviour_policy",
    "seed",
    "device",
    "train_return_mean",
    "train_return_std",
    "policy_loss",
    "value_loss",
    "td_loss",
    "entropy",
    "kl",
    "delta_tv",
    "delta_tv_ci_lo",
    "delta_tv_ci_hi",
    "delta_kl",
    "delta_chi2",
    "delta_sup",
    "delta_mmd2",
    "delta_ks",
    "delta_tv_marginal",
    "delta_tv_conditional",
    "min_propensity",
    "ess_ratio",
    "overlap_at_1e-2",
    "tail_mass_top10pct",
    "coverage_action_freq_min",
    "coverage_ess_histogram",
    "propensity_calibration_ece",
    "pi_b_recovery_kl",
    "bound_width_mean",
    "bound_width_max",
    "bound_width_std",
    "n_arms_with_informative_bound",
    *_BOUND_COLUMNS_PER_ARM,
    "backdoor_residual_mean",
    "backdoor_residual_max",
    "target_support_overlap",
    "cond_mi_r_z_given_sa",
    "alpha_conf",
    "bias_strength",
    "expose_z",
    "pi_b_known",
    "beh_depends_on_u",
    "id_status",
    "lr",
    "grad_norm",
]

EVAL_COLUMNS = [
    "step",
    "episode",
    "wall_time",
    "cell",
    "env_name",
    "env_fidelity",
    "algorithm",
    "behaviour_policy",
    "seed",
    "eval_return_mean",
    "eval_return_std",
    "delta_tv",
    "delta_tv_ci_lo",
    "delta_tv_ci_hi",
    "delta_kl",
    "delta_chi2",
    "delta_sup",
    "delta_mmd2",
    "delta_ks",
    "min_propensity",
    "ess_ratio",
    "overlap_at_1e-2",
    "tail_mass_top10pct",
    "coverage_action_freq_min",
    "coverage_ess_histogram",
    "propensity_calibration_ece",
    "pi_b_recovery_kl",
    "bound_width_mean",
    "bound_width_max",
    "bound_width_std",
    "n_arms_with_informative_bound",
    *_BOUND_COLUMNS_PER_ARM,
    "backdoor_residual_mean",
    "backdoor_residual_max",
    "target_support_overlap",
    "cond_mi_r_z_given_sa",
    "alpha_conf",
    "bias_strength",
    "expose_z",
    "pi_b_known",
    "beh_depends_on_u",
    "id_status",
    "eval_oracle_return_mean",
    "eval_oracle_return_std",
    "delta_tv_beh",
    "ece",
]

PERTURBED_COLUMNS = [
    "step",
    "episode",
    "wall_time",
    "cell",
    "env_name",
    "algorithm",
    "behaviour_policy",
    "seed",
    "eps_T",
    "eps_R",
    "eval_perturbed_return_mean",
    "eval_perturbed_return_std",
    "D_env_KS",
    "D_bisim",
]

EVAL_PERTURBED_COLUMNS = [
    "seed",
    "cell",
    "env",
    "algorithm",
    "behaviour",
    "alpha_conf",
    "bias_strength",
    "eps_T",
    "eps_R",
    "eval_perturbed_return_mean",
    "eval_perturbed_return_std",
    "D_env_KS",
    "D_bisim",
]
