from __future__ import annotations

TRAIN_COLUMNS = [
    "step",
    "episode",
    "wall_time",
    "cell",
    "env_name",
    "env_fidelity",
    "algorithm",
    "behaviour_policy",
    "seed",
    "device",
    "train_return_mean",
    "train_return_std",
    "policy_loss",
    "value_loss",
    "td_loss",
    "entropy",
    "kl",
    "delta_tv",
    "delta_kl",
    "delta_chi2",
    "delta_sup",
    "delta_tv_marginal",
    "delta_tv_conditional",
    "lr",
    "grad_norm",
]

EVAL_COLUMNS = [
    "step",
    "episode",
    "wall_time",
    "cell",
    "env_name",
    "env_fidelity",
    "algorithm",
    "behaviour_policy",
    "seed",
    "eval_return_mean",
    "eval_return_std",
    "eval_holdout_return_mean",
    "eval_holdout_return_std",
    "delta_tv",
    "delta_kl",
    "delta_chi2",
    "delta_sup",
    "eval_oracle_return_mean",
    "eval_oracle_return_std",
]
